export const user_data = {
  id: 1,
  username: 'jordowag',
  first_name: 'Jordan',
  events: [
    {
      id: 1,
      created_by: 1,
      name: 'Shebang',
      description: 'An event!',
      date: new Date('09/29/1990'),
      people: 5,
      attended: true,
      points: 3,
    },
    {
      id: 2,
      created_by: 2,
      name: 'Dinner',
      description: 'An event!',
      date: new Date('09/30/1990'),
      people: 6,
      attended: false,
      points: 5,
    },
    {
      id: 3,
      created_by: 1,
      name: 'Karaoke',
      description: 'An event!',
      date: new Date('09/21/1990'),
      people: 4,
      attended: true,
      points: 5,
    },
    {
      id: 4,
      created_by: 1,
      name: 'Karaoke pt 2',
      description: 'An event!',
      date: new Date('10/18/2019'),
      people: 4,
      attended: true,
      points: 5,
    },
    {
      id: 4,
      created_by: 2,
      name: 'Dinner pt 2',
      description: 'An event!',
      date: new Date('10/25/2019'),
      people: 4,
      attended: true,
      points: 5,
    },
  ],
},